openapi: 3.1.0
x-stoplight:
  id: v2pvw9niawdll
info:
  title: joke-api
  version: '1.0'
servers:
  - url: 'https://official-joke-api.appspot.com/'
paths:
  /random_joke:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
        '500':
          description: Internal Server Error
      operationId: getRandomjoke
      x-stoplight:
        id: 9xvcmlq3ip54k
components:
  schemas: {}
